dist: bionic
language: minimal
arch:
  - ppc64le
  - amd64
env:
  - BUILD_TYPE=Release
  - BUILD_TYPE=Debug


cache:
  directories:
    $HOME/cmake

install:
  - ci/install_deps.sh || travis_terminate 1;

script:
  - ci/build.sh || travis_terminate 1;